### ISSUE TITLE
python 3.7 support

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/kiwipy#25]
I see that the latest tests are [currently failing on python 3.7](https://travis-ci.org/aiidateam/kiwipy/jobs/508810366)

Is it planned to support python 3.7?
It looks to me like kiwipy and plumpy are the only aiida-core dependencies that are not yet python3.7 ready (?)

**Comment by ltalirz** [comment]
mentioning @sphuber and @muhrin

**Comment by sphuber** [comment]
In principle we should be able to support python 3.7 The only problem was with Travis. To run 3.7 we need to build on xenial, which still needs the `sudo: required` fix and it unfortunately does not have the rabbitmq-server service installed. I managed to get it running by going through `sudo apt` instead. If we enable this for `kiwipy` and then `plumpy`, we would also have to do the same changes for `aiida-core` if we want to test it on `3.7` there as well. That would bring the number of builds to 12 though and builds are already slow.

**Comment by ltalirz** [comment]
I would say let's definitely enable the test for kiwipy and plumpy.
For aiida-core we can decide. I would vote to simply switch from 3.6 to 3.7.
Otherwise we can also add those tests on azure pipelines or similar (more for information, accepting failures there)
