### ISSUE TITLE
Compatibility states python 3.5 but should fail

### ISSUE THREAD

**Issue by sphuber** [aiidateam/kiwipy#34]
In `BroadcastFilter._ensure_filter` we find the following line:
```
if isinstance(filter_value, typing.re.Pattern):
```
which in python 3.5.2 will raise
```
TypeError: Type aliases cannot be used with isinstance().
```
Apparently this also goes for all older python3 version: https://github.com/pandas-dev/pandas/issues/21078
We should either replace it with a different check, or remove python 3.4 and 3.5 from compatibility list.

**Comment by muhrin** [comment]
Interesting...I have zero interesting in supporting 3.4 but I think 3.5 support is worth giving this a little of my time.  I'll have a look.
