### ISSUE TITLE
Tests incompatible with `pytest-asyncio` = 0.11.0

### ISSUE THREAD

**Issue by muhrin** [aiidateam/kiwipy#47]
Looks like there was some incompatibility introduced with `pytest-asyncio` 0.11.0.  Manifestation can be seen here:

https://travis-ci.com/github/muhrin/kiwipy/builds/161204481

**Comment by sphuber** [comment]
I think this may have been fixed with [this PR on `pytest-asyncio`](https://github.com/pytest-dev/pytest-asyncio/pull/156) so updating to `0.12.0` should solve the problem. Don't think it is worth it trying to add a workaround on our side so we can continue supporting `pytest-asyncio<0.12.0`
