### ISSUE TITLE
conda build hangs after running test suite

### ISSUE THREAD

**Issue by ltalirz** [aiidateam/kiwipy#5]
I'm in the process of adding kiwipy to conda-forge and, for some reason, the tests hang:
https://circleci.com/gh/conda-forge/staged-recipes/27488?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

When I clone kiwipy and run the tests locally it works, but I can reproduce the problem locally with conda build. To reproduce:
 * clone the recipe from https://github.com/conda-forge/staged-recipes/pull/5951
 * `cd staged-recipes/recipes/kiwipy`
 * `conda build . -c conda-forge`

Any ideas what might be causing this?

**Comment by ltalirz** [comment]
One thing - obviously, there will be no rabbitmq server running in the build environment (while I do have on running locally).
What happens with the tests in this case?

**Comment by sphuber** [comment]
I tried to reproduce hanging tests when there is no `rabbitmq-server` by stopping it on my machine. With the current `develop` the tests just fail and do not hang. Is this bug still relevant on the conda build?

**Comment by ltalirz** [comment]
I'm no longer testing on conda-forge - and I've been told they anyhow don't recommend running more than the most basic tests (e.g. importing the module). Closing.
