### ISSUE TITLE
The task queue message TTL is probably too short

### ISSUE THREAD

**Issue by sphuber** [aiidateam/kiwipy#57]
Currently it is set to 1 week:
https://github.com/aiidateam/kiwipy/blob/45a74feb0bacce09468d46c8ff4f225c3d0ba84b/kiwipy/rmq/defaults.py#L20
But for a lot of applications this will be too short as tasks are supposed to be persistent and typically one would expect this to be more than a week. We should either make the default larger or make sure it is easy to configure

**Comment by zhubonan** [comment]
I think a few months (six maybe) sounds reasonable, one week is certain too short. The typical downtime for maintenance (or recover from a hack...) would be in the order of weeks at longest hopefully.


Should probably also document this somewhere (with the recovery procedures maybe?), as the current documentation gave the impression that the processes are resilient to daemon shutdowns, which is technically correct, just extra steps are needed to restart them.

**Comment by sphuber** [comment]
Fixed in PR #59 and released in v0.5.4
