### ISSUE TITLE
Question: How to integrate with Flask?

### ISSUE THREAD

**Issue by kashcode** [aiidateam/kiwipy#95]
subj.

**Comment by muhrin** [comment]
Thanks for getting in touch @kashcode .

Could you elaborate a little please?  From my (limited) understanding of flask it is used to create endpoints for web applications while `kiwipy` is used for sending various types of message (broadcast, tasks, remote-procedure-call, etc).

For what part of your application would you like to use `kiwipy`?

**Comment by muhrin** [comment]
Closing this issue.  Feel free to re-open if you'd still like an answer.
